#!/usr/bin/env python
from tyr.utilities.create_cm_automation_servers import (build_mongo_servers,
                                                        ACCEPTED_JSON_STRUCT,
                                                        JSON_CLUSTER)
import click


@click.group()
def deployment():
  pass


@deployment.command()
@click.argument('json_file', type=click.Path(exists=True), required=False)
def deploy_servers(json_file):
  build_mongo_servers(json_file)


@click.group()
def example():
  pass


@example.command()
@click.option('--cluster', is_flag=True)
@click.option('--rs', is_flag=True)
def show_example(cluster, rs):
    if cluster:
        print JSON_CLUSTER
    elif rs:
        print ACCEPTED_JSON_STRUCT

create_cm_automation_servers = click.CommandCollection(sources=[deployment, example])

if __name__ == '__main__':
    create_cm_automation_servers()
